export * from "./balance";
export * from "./chat";
export * from "./conflict";
export * from "./events";
export * from "./forest";
export * from "./forestgen";
export * from "./game";
export * from "./hex";
export * from "./mapgen";
export * from "./protocol";
export * from "./rewards";
export * from "./rng";
export * from "./season";
export * from "./social";
export { makeTile, ownedTilesOf, ownedCountOf, ownerCounts, neighbourTiles, tilesWithin, tilesEpoch, ownerVersion, tileKey, type TileFields } from "./tile-index";

export const GAME_NAME = "Mycelium";
export { botPlay } from "./sim/week";
export { botAct } from "./sim/fight";
export { botDiplomacy } from "./sim/diplomacy";
